name: cerebra-epistasis

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.10
  - pytorch
  - numpy
  - pandas
  - transformers
  - einops
  - filelock
  - pip
  - pip:
      - iterative-stratification